CBQE-5762: TAF jobs failing due to rerun_jobs script runs into UnambiguousTimeoutException
TAF jobs are failing due to
following exception when trying to
get documents for re_runs
com.couchbase.client.core.error.UnambiguousTimeoutException: com.couchbase.client.core.error.UnambiguousTimeoutException: GetRequest {"cancelled":true,"completed":true,"coreId":1,"idempotent":true,"reason":"TIMEOUT","requestId":3,"requestType":"GetRequest","retried":14,"retryReasons":["BUCKET_OPEN_IN_PROGRESS"],"service":{"bucket":"rerun_jobs","collection":"_default","documentId":"centos_collections_rebalance_P0_7.0.0-2017","opaque":"0x4","scope":"_default","type":"kv"},"timeoutMs":2500,"timings":{"totalMicros":2597178}}
Adding a small sleep after opening
bucket connection to mitigate the
issue.

Change-Id: Id55bd9f56f94af046847a53113eb229198d5ed55
Reviewed-on: http://review.couchbase.org/c/TAF/+/127765
Tested-by: Balakumaran G <balakumaran.gopal@couchbase.com>
Reviewed-by: Balakumaran G <balakumaran.gopal@couchbase.com>