Revert "CBQE-8314:test case for encryption at rest class"
This reverts commit 687fa1807f6075903e9588a14f219fa2892da055.

Reason for revert: In Jython 2.7.2, ImportError: cannot import name log2

Change-Id: I6a1f508f3a618a8f84d89c51ca477000efaec7b9
Reviewed-on: https://review.couchbase.org/c/TAF/+/221265
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Vibhav S P <vibhav.sp@couchbase.com>