Tasks: Generate unique thread_names instead of using time()
When attempting to repro MB-55709 on a macOS cluster_run, KeyError
exception was observed to be thrown from get_task_result() when trying
to lookup a task:

    2023-03-03 12:12:17,572 | infra | INFO    | pool-5-thread-15 | [task:complete_task:106] Thread 'StatsWaitTask_default_num_items_for_persistence_1677845537.36' completed
    2023-03-03 12:12:17,572 | infra | INFO    | pool-5-thread-5 | [task:complete_task:106] Thread 'StatsWaitTask_default_num_items_for_persistence_1677845537.36' completed
    2023-03-03 12:12:17,572 | infra | INFO    | pool-5-thread-17 | [task:complete_task:106] Thread 'StatsWaitTask_default_num_items_for_persistence_1677845537.36' completed
    ERROR

    ======================================================================
    ERROR: test_crash_during_dedupe (storage.magma.magma_crash_recovery.MagmaCrashTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "pytests/storage/magma/magma_crash_recovery.py", line 29, in setUp
        super(MagmaCrashTests, self).setUp()
      File "pytests/storage/magma/magma_base.py", line 82, in setUp
        self.initial_load()
      File "pytests/storage/storage_base.py", line 574, in initial_load
        self.wait_for_doc_load_completion(task)
      File "pytests/storage/storage_base.py", line 355, in wait_for_doc_load_completion
        self.bucket_util._wait_for_stats_all_buckets(
      File "couchbase_utils/bucket_utils/bucket_ready_functions.py", line 2581, in _wait_for_stats_all_buckets
        self.task.jython_task_manager.get_task_result(task)
      File "lib/Jython_tasks/task_manager.py", line 25, in get_task_result
        future = self.futures[task.thread_name]
    KeyError: 'StatsWaitTask_default_num_items_for_persistence_1677845537.36'

I believe the issue here that tasks are not being given unique
thread_names - see the 3 log lines above where tasks running on 3
different threads have the same name. From the code, we can see that
StatsWaitTask (and other tasks) generate their task name by adding a
time-based suffix to a fixed string:

    class StatsWaitTask(Task):
        def __init__(self, shell_conn_list, bucket, stat_cmd, stat, comparison,
                     value, timeout=300):
            super(StatsWaitTask, self).__init__("StatsWaitTask_%s_%s_%s"
                                                % (bucket.name,
                                                   stat,
                                                   str(time.time())))

                                                       ^^^^^^^^^^^

time.time() only returns a value to 2 decimal places on python2 (on
macOS):

    $ python2
    Python 2.7.18 (default, Jul 22 2022, 12:12:21)
    [GCC Apple LLVM 13.1.6 (clang-1316.0.21.2.5)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import time
    >>> print(time.time())
    1677852282.29

Interestingly Python3 has a better precision:

    $ python3
    Python 3.10.9 (main, Dec 15 2022, 10:44:50) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import time
    >>> print(time.time())
    1677852328.08045

Fix this issue by not using a (low resolution) timestamp to generate
uniqueness, simply use a static serial number in the Task class. This
is implemented with AtomicInteger to ensure the generated number is
unique even if generated from multiple threads.

Change-Id: Id1b133f7a146de26d66ed689fc86bf82e346d231
Reviewed-on: https://review.couchbase.org/c/TAF/+/187779
Reviewed-by: Ashwin <ashwin.govindarajulu@couchbase.com>
Tested-by: Dave Rigby <daver@couchbase.com>